export enum EmailType {
    OTP_VERIFICATION = "OTP_VERIFICATION",
    WELCOME_VERIFIED = "WELCOME_VERIFIED",
    RESET_PASSWORD_OTP = "RESET_PASSWORD_OTP",
    PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS",
}